### ISSUE TITLE
Sony Open Device Support for Mediatek SOC

### ISSUE THREAD

**Issue by bigrammy** [sonyxperiadev/device-sony-common#806] opened 2020-12-28 17:07 UTC
I am pretty tired of people blaming MEDIATEK all the time!!
The problems we have is with Sony NOT MediaTek.
There is plenty of MediaTek Sources which are open but Sony add their own stuff which we find hard to overcome. Sony removed MediaTek's SPFlashtool support in favour of Sony's S1 Protocol which has no way to recover the device once soft bricked.
This makes things very difficult since we cannot replace the preloader and or LK.
Sony should release open preloader, lk, logo and secro so we can flash those without bricking the device.
Earlier Sony MTK devices used to have "TEST" images included in the firmware packages which were flashed on bootloader unlocked devices but these images used to brick the phones just see the "flashtool" threads regarding the C4, M5 and variants of.
From the XA on these "TEST" images were removed and the bricking of MTK's ended.
So ask your OEM's like Arima to provide the standard MediaTek or fully open Sony ROM's for the Sony L1 code name SM31 Pine for example.
Nothing to do with MEDIATEK it's 100% OEM's preventing us doing anything on these cheaper devices hence why we get no OS upgrades on the L devices the L1 released on N and is still on N today Same for the L2 and probably the L3 and L4.

As said before I am happy to donate a Sony L1 and provide the mt6737 source code to any leading Sony Xperia Dev who thinks he/she is capable.

**Comment by ix5** [comment] 2020-12-28 17:49
Duplicate of https://github.com/sonyxperiadev/device-sony-common/issues/777#issuecomment-751788749

Whether or not the blame lies with Sony, you know when buying a MTK device you're gonna have a bad time developing. Start a petition, write to the CEO, whatever, ranting on the bug tracker won't do your cause much good.

**Comment by bigrammy** [comment] 2020-12-28 18:29
"when buying a MTK device you're gonna have a bad time developing"
Why would that be please explain? 
Team MAD didn't find it too difficult but maybe they were real devs unlike some who simply call _make_ and wait for it to compile. Not aimed at you but the mediatek haters who are just pretend to be dev's and have no real idea but feel it's OK to say it because they read some old blog post from 6 years ago.  
I can give you all the source code you like the problem lays with Sony as I said and since I can see no **FORMAL** way to ask for support _Ranting_ seems logical 
It's help we want not a argument about misinformed pre conceptions about MediaTek. 
It's OEM's who mess things up installing preloaders and lk's that block the RIL from working not Mediatek.

SONY_S1_SUPPORT = yes
SONY_ONESW_MULTI_SIM_SUPPORT = yes
ARIMA_SMARTCARDSERVICE=yes

**Comment by jmpfbmx** [comment] 2020-12-28 18:51
I think the same as @bigrammy he has the reason
We have been working hardly on the XPERIA L1, you can see our work at github.com/PineDevelopment
And we couldn't fix RIL, all MTK SONY Devices has the same err.
So if were supported by SODP all would be easier for us.
We can provide all you want.
If SONY don't use .sin format we will can flash by SP Flash Tool and we could build ALPS and upstream easier but no we can't
So pls consider our petition.
And pls @ix5 explain to me: `"when buying a MTK device you're gonna have a bad time developing"`this too
Thanks.
Regards,
Jose

**Comment by Paulbouchara** [comment] 2020-12-28 18:56
> I think the same as @bigrammy he has the reason
> We have been working hardly on the XPERIA L1, you can see our work at github.com/PineDevelopment
> And we couldn't fix RIL, all MTK SONY Devices has the same err.
> So if were supported by SODP all would be easier for us.
> We can provide all you want.
> If SONY don't use .sin format we will can flash by SP Flash Tool and we could build ALPS and upstream easier but no we can't
> So pls consider our petition.
> And pls @ix5 explain to me: `"when buying a MTK device you're gonna have a bad time developing"`this too
> Thanks.
> Regards,
> Jose

Regarding .sin you can always convert those to standard .img or whatever the tool uses to flash images
Other than that, as we already discussed for RIL there might be some telephony injection or special magic that relies on modem-switcher that seems different than our qcom based handling

**Comment by ix5** [comment] 2020-12-28 18:57
Open Devices is working _with_ the support of the OEM (Sony) _and_ the BSP provider (Qualcomm), not _against_ them as most MTK ports are.
It's great that you guys are such self-described "great hackers", but the simple fact is that MTK devices are shipped on very tight margins and as such, OEMs are quite wary of offering developer incentives such as BLU or are quite late with kernel releases.

I'm sure @jerpelea (who had to fight very hard to get the Qcom-based devices to where they are now) can try to escalate your issues with corpo people, but since the situation is as ever with low-end phones, I'm giving it little chances.

**Comment by jmpfbmx** [comment] 2020-12-28 18:58
@Paulbouchara yes i know that we can convert .sin into .img but we can't flash with SP Flash Tool that is one of our problems.
And about RIL yes, i tried what we discussed but didn't work.
I have tried even to use some stock apps that contains RIL things and nothing.
IDK what happens with it but we couldn't make it work :(

**Comment by bigrammy** [comment] 2020-12-28 20:38
> EDIT: Also, please use the [bug tracker](https://github.com/sonyxperiadev/bug_tracker/issues/) instead.

I am not having a go at this project what you guys have done is nothing short of a miracle. I think sony make some great devices and i have the m5, c4, xa, xa1 and L1 (all MediaTek) I have held off buying the L3 and L4 because of the reasons stated and I ended up buying a Xiaomi Redmi Note 8 Pro (Begonia)(MTK) instead because Xiaomi release the kernel sources so there is some pretty active development going on.
If @jerpelea could bump us up the sony agenda that would be great if he would get one of these devices in his hands then that would be great. 
Grab one then take a look then give us your thoughts If it's not going to happen I will abandon Sony MTK Devices as others have. Picking up a used Sony MTK used will cost very little but if anyone is struggling with the finances I have on here

**Comment by jerpelea** [comment] 2020-12-29 08:30
@bigrammy 
For the moment we are supporting only QCOM devices

**Closed by jerpelea** 2020-12-29 08:30 UTC

**Comment by bigrammy** [comment] 2020-12-29 10:27
@jerpelea 

Understood but please be sure to let us know if anything changes with regard to MTK support.
If any Info about what Sony do with regard to the RIL and SIM detection on these MediaTek devices becomes available then please let us know. Maybe you could ask on our behalf since we have everything else working on these devices. :(

**Comment by jerpelea** [comment] 2020-12-29 13:09
since MTK is not included in this program I can't promise anything
